import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/Navigation/Navigation";
import FooterComp from "@/components/Footer/Footer";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "EIFPE",
  description: "Eagle International Films Production And Entertainement"
};

export default function RootLayout({ children }) {
  return (
    <>
      <Head>
        <title>EIFPE</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <html lang="en">
        <body className={inter.className}>
          <Navigation />
          {children}
          <FooterComp />
        </body>
      </html>
    </>
  );
}
